	SUBROUTINE UMAT (STRESS,STATEV,DDSDDE,SSE,SPD,    &
					SCD,RPL,DDSDDT,DRPLDE,DRPLDT,     &
					STRAN,DSTRAN,TIME,DTIME,TEMP,     &
					DTEMP,PREDEF,DPRED,CMNAME,NDI,    &
					NSHR,NTENS,NSTATV,PROPS,NPROPS,  &
					COORDS,DROT,PNEWDT,CELENT,DFGRD0, &
					DFGRD1,NOEL,NPT,LAYER,KSPT,       &
					JSTEP,KINC)
					
					
					
	implicit none
	! PROPS(1) - E
	! PROPS(2) - NU

	character*80,intent(in)::CMNAME
	INTEGER(kind=4),intent(in)::NTENS,NSTATV,NPROPS,&
								NDI,NSHR,NOEL,NPT,&
								KSPT,JSTEP,KINC,LAYER

	REAL(KIND=8)::SSE,SPD,SCD,RPL,DRPLDT,&
				  DTIME,TEMP,DTEMP,PNEWDT,CELENT

	REAL(KIND=8)::STRESS(NTENS),STATEV(NSTATV),&
				  DDSDDE(NTENS,NTENS),DDSDDT(NTENS),&
				  DRPLDE(NTENS),STRAN(NTENS),&
				  DSTRAN(NTENS),TIME(2),&
				  PREDEF(1),DPRED(1),&
				  PROPS(NPROPS),COORDS(3),&
				  DROT(3,3),DFGRD0(3,3),&
				  DFGRD1(3,3)
				  
	REAL(KIND=8)::EMOD,NU,ALAME,BLAME,CLAME

	!-----------------------
	REAL(8),PARAMETER::ONE=1.0D0,TWO=2.0D0
	REAL(8):: LLAME, MLAME
	INTEGER(8)::I,J
	!INTEGER,PARAMETER:: N1=6,N2=6
	EMOD=PROPS(1)
	NU=PROPS(2)

	LLAME=Emod*NU/(ONE+NU)/(ONE-2*NU)
	MLAME=Emod/2/(1+NU)

	DDSDDE = 0


	DDSDDE(1,1)=LLAME+2*MLAME
	DDSDDE(1,2)=LLAME
	DDSDDE(1,3)=LLAME
	DDSDDE(2,2)=LLAME+2*MLAME
	DDSDDE(2,3)=LLAME
	DDSDDE(3,3)=LLAME+2*MLAME
	DDSDDE(4,4)=LLAME
	DDSDDE(5,5)=LLAME
	DDSDDE(6,6)=LLAME


	STRESS = STRESS + MATMUL(DDSDDE,DSTRAN)

	print *, 'Hello, World!'
	print *, DDSDDE
	  DO I=1,NTENS
	      DO J=1,NTENS
	      STRESS(I)=STRESS(I)+DDSDDE(I,J)*DSTRAN(J)
	      ENDDO
	     ENDDO
	PRINT *, STRESS
        write (*,"(6(1x,F10.2))") transpose(DDSDDE)
RETURN
end
